project:
  type: website
  output-dir: _site

quartodoc:
  package: lrassume
  sections:
    - title: Functions
      desc: All functions in the package
      contents:
        - check_independence
        - check_linearity
        - check_multicollinearity_vif
        - check_homoscedasticity

website:
  title: "lrassume"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Tutorials"
        contents:
          - tutorials/getting-started.qmd
          - tutorials/independence.qmd
          - tutorials/linearity.qmd
          - tutorials/multicollinearity.qmd
          - tutorials/homoscedasticity.qmd
      - text: "API Reference"
        href: reference/index.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    code-copy: true
    code-overflow: wrap