name: lr_assume
channels:
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - bcrypt=5.0.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cffi=2.0.0
  - colorama=0.4.6
  - copier=9.11.0
  - cryptography=46.0.3
  - dunamai=1.25.0
  - eval-type-backport=0.2.2
  - eval_type_backport=0.2.2
  - funcy=2.0
  - importlib_resources=6.5.2
  - invoke=2.2.1
  - jinja2=3.1.6
  - jinja2-ansible-filters=1.3.2
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libzlib=1.3.1
  - markupsafe=3.0.3
  - ncurses=6.5
  - openssl=3.6.0
  - packaging=25.0
  - paramiko=4.0.0
  - pathspec=0.12.1
  - pip=25.3
  - platformdirs=4.5.1
  - plumbum=1.10.0
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pynacl=1.6.2
  - python=3.14.2
  - python_abi=3.14
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.3
  - questionary=2.1.1
  - readline=8.3
  - six=1.17.0
  - tk=8.6.13
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wcwidth=0.2.14
  - yaml=0.2.5
  - zipp=3.23.0
  - zstd=1.5.7